# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -roman.sercent@gmail.com
    on_success: never # default: change
    on_failure: always # defa,ult: always

#This shit add by Markelov Roman
env:
  global:
    - CODECOV_TOKEN="308b85e1-d758-4e5a-b2ab-4a9d8847f048"